api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/packages/api_platform'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    defaults:
        # disable REST
        # @see https://github.com/api-platform/core/issues/2796#issuecomment-606729715
        item_operations:
            get:
                controller: ApiPlatform\Core\Action\NotFoundAction
                read: false
                output: false
        collection_operations:
            get:
                controller: ApiPlatform\Core\Action\NotFoundAction
                read: false
                output: false
