App\Entity\Post:
  attributes:
    filters:
      - api.post.date_filter
  graphql:
     item_query: ~
     collection_query: ~
     create:
       mutation: App\ApiPlatform\GraphQL\Resolver\Post\CreateResolver
       args:
         title:
           type: String!
         body:
           type: String!
         published:
           type: Boolean
         date:
           type: String
     update: ~
     delete: ~
